### ISSUE TITLE
Vault Admins not having access to PSM safe to manage PSM local accounts

### ISSUE THREAD

**Issue by paulpalayur** [pCloudServices/Set-DomainUser#5]
Hi,

If the customer is using PSM local accounts then can we extend this script or have another script to assign vault admins access to PSM safe to manage the PSM local accounts. I see this gap in IdentityUM. Ideally another script will be good. I have tweaked this script in my lab and made it working. Happy to share that.

**Comment by hjbotha-cybr** [comment]
this has been added to the safe creation flow
